import { ApiProperty } from '@nestjs/swagger';

/**
 *request DTO of token when user login in process
 * @author Afzal Mansuri 
 */
export class TokenPayloadDto {
  /**
   * Timw when token will be expires
   */
  @ApiProperty()
  expiresIn: number;

  /**
   * autogenerated token when user login successfull
   */
  @ApiProperty()
  accessToken: string;

  /**
   * @param data object containing `expiresIn` and `accessToken` 
   */
  constructor(data: { expiresIn: number; accessToken: string }) {
    this.expiresIn = data.expiresIn;
    this.accessToken = data.accessToken;
  }
}
